'use strict'; 
//Autogenerated using Sequelize-CLI
const fs = require('fs');
const path = require('path');
const Sequelize = require('sequelize');
const basename = path.basename(__filename);
const env = process.env.NODE_ENV || 'development';
const config = require(__dirname + '/../config/db.config.json')[env];
const db = {};

/* Connects to the database. */
let sequelize;
if (config.use_env_variable) {
  sequelize = new Sequelize(process.env[config.use_env_variable], config);
} else {
  sequelize = new Sequelize(config.database, config.username, config.password, config);
}

/* Reading all the files in the directory and then filtering them to only include the files that end in
.js. Then it is requiring the files and adding them to the db object. */
fs
  .readdirSync(__dirname)
  .filter(file => {
    return (file.indexOf('.') !== 0) && (file !== basename) && (file.slice(-3) === '.js');
  })
  .forEach(file => {
    const model = require(path.join(__dirname, file))(sequelize, Sequelize.DataTypes);
    db[model.name] = model;
  });

/* Loops through the db object and checks if the model has an associate
function. If it does, it calls the associate function. */
Object.keys(db).forEach(modelName => {
  if (db[modelName].associate) {
    db[modelName].associate(db);
  }
});

/* Exporting the db object. */
db.sequelize = sequelize;
db.Sequelize = Sequelize;

module.exports = db;
