on:
  pull_request: 
    branches: ["main"]
  push:
    branches: ["main"]
jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2     # checkout the repo
      - run: npm ci                   # install packages
      - run: npm test -- tests/**/*.js                # run tests (configured to use mocha and chai)

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: MOCHA Tests            # Name of the check run which will be created
          path: reports/mocha-*.json    # Path to test results
          reporter: mocha       # Format of test results
